repository: superyaooo/Blog  # needed to avoid "No repo name found." error when running jekyll locally on windows

# Setup
title: Coding & Blogging
subtitle: beep boop beep beep boop...
description: My tech blog via Github
baseurl: /Blog
site-url: https://github.com/superyaooo/Blog

# Author
author-name: Yao Wang
author-url: http://yaowangdev.com/
